/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Dnd5E = Token | Class | Race;
/**
 * Manually declare the initiative bonus of the token
 */
export type InitiativeBonus = number;
/**
 * Manually declare the proficiency bonus of the token
 */
export type ProficiencyBonus = number;

/**
 * A token describes the properties and stats of a player character, NPC or monster
 */
export interface Token {
  type: "token";
  refName: string;
  ID?: string;
  name: string;
  icon?: string;
  race?:
    | Race
    | {
        idRef: string;
      }
    | {
        nameRef: string;
      };
  alignment?: string;
  classes?: (
    | Class
    | {
        idRef: string;
      }
    | {
        nameRef: string;
      }
  )[];
  inspiration?: boolean;
  attributes: {
    STR: number;
    DEX: number;
    CON: number;
    INT: number;
    WIS: number;
    CHA: number;
    [k: string]: unknown;
  };
  initiative?: InitiativeBonus;
  proficiency?: ProficiencyBonus;
  vulnerabilities?: string[];
  resistances?: string[];
  immunities?: string[];
}
/**
 * A race
 */
export interface Race {
  type?: "race";
  refName: string;
  ID?: string;
  label?: string;
}
/**
 * A class contains a set of features with modifiers that describe the abilites it can use and any bonuses
 */
export interface Class {
  type?: "class";
  refName: string;
  ID?: string;
  label?: string;
}
